"""
YANG keyword constants used by parser modules.

All YANG statement/type keywords are represented as plain identifier lexemes.
"""

# Core module/header keywords
MODULE = "module"
YANG_VERSION = "yang-version"
NAMESPACE = "namespace"
PREFIX = "prefix"
ORGANIZATION = "organization"
CONTACT = "contact"
DESCRIPTION = "description"
REVISION = "revision"
REFERENCE = "reference"

# Definitions
TYPEDEF = "typedef"
IDENTITY = "identity"
BASE = "base"
TYPE = "type"
GROUPING = "grouping"
USES = "uses"
REFINE = "refine"
FEATURE = "feature"
IF_FEATURE = "if-feature"
EXTENSION = "extension"
ARGUMENT = "argument"
YIN_ELEMENT = "yin-element"

# Data nodes/statements
CONTAINER = "container"
LIST = "list"
LEAF = "leaf"
LEAF_LIST = "leaf-list"
ANYDATA = "anydata"
ANYXML = "anyxml"
CHOICE = "choice"
CASE = "case"
MUST = "must"
WHEN = "when"
PRESENCE = "presence"
KEY = "key"
MIN_ELEMENTS = "min-elements"
MAX_ELEMENTS = "max-elements"
ORDERED_BY = "ordered-by"
MANDATORY = "mandatory"
DEFAULT = "default"
ERROR_MESSAGE = "error-message"
ERROR_APP_TAG = "error-app-tag"

# Type substatements and builtins
BINARY = "binary"
BITS = "bits"
BOOLEAN = "boolean"
DECIMAL64 = "decimal64"
EMPTY = "empty"
ENUMERATION = "enumeration"
IDENTITYREF = "identityref"
INSTANCE_IDENTIFIER = "instance-identifier"
INT8 = "int8"
INT16 = "int16"
INT32 = "int32"
INT64 = "int64"
LEAFREF = "leafref"
STRING_KW = "string"
UINT8 = "uint8"
UINT16 = "uint16"
UINT32 = "uint32"
UINT64 = "uint64"
UNION = "union"
PATH = "path"
REQUIRE_INSTANCE = "require-instance"
ENUM = "enum"
VALUE = "value"
STATUS = "status"
BIT = "bit"
POSITION = "position"
PATTERN = "pattern"
LENGTH = "length"
FRACTION_DIGITS = "fraction-digits"
RANGE = "range"
TRUE = "true"
FALSE = "false"

# Cross-module/submodule
IMPORT = "import"
INCLUDE = "include"
REVISION_DATE = "revision-date"
AUGMENT = "augment"
SUBMODULE = "submodule"
BELONGS_TO = "belongs-to"

# Unsupported statements
DEVIATION = "deviation"
RPC = "rpc"
ACTION = "action"
NOTIFICATION = "notification"
INPUT = "input"
OUTPUT = "output"

UNSUPPORTED_CONSTRUCT_KEYWORDS = frozenset(
    {DEVIATION, RPC, ACTION, NOTIFICATION, INPUT, OUTPUT}
)
